name: cook_with_engineer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0
  cached_network_image: ^3.2.3
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  image_picker: ^1.1.2
  file_picker: ^10.0.0
  permission_handler: ^11.4.0  # Updated to latest version
  
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true  # ✅ স্পেস ঠিক করা হয়েছে
