// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjo1LA_kDIjGpwoJdGAgr8nc4T3gllxms',
    appId: '1:942621156943:web:4c1b6cd559c37e6072ac3a',
    messagingSenderId: '942621156943',
    projectId: 'newsapp-4210a',
    authDomain: 'newsapp-4210a.firebaseapp.com',
    databaseURL: 'https://newsapp-4210a-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-4210a.firebasestorage.app',
    measurementId: 'G-050J9BR5JX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIC3x-s_cw7jr0krXNHm7cKMYVIbay6bU',
    appId: '1:942621156943:android:74b2060f23617ed672ac3a',
    messagingSenderId: '942621156943',
    projectId: 'newsapp-4210a',
    databaseURL: 'https://newsapp-4210a-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-4210a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvjNcvM8XhqlghtHDpEeYSuPBmLU2Tyiw',
    appId: '1:942621156943:ios:c028bcb54523c93572ac3a',
    messagingSenderId: '942621156943',
    projectId: 'newsapp-4210a',
    databaseURL: 'https://newsapp-4210a-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-4210a.firebasestorage.app',
    iosBundleId: 'com.example.cookWithEngineer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvjNcvM8XhqlghtHDpEeYSuPBmLU2Tyiw',
    appId: '1:942621156943:ios:c028bcb54523c93572ac3a',
    messagingSenderId: '942621156943',
    projectId: 'newsapp-4210a',
    databaseURL: 'https://newsapp-4210a-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-4210a.firebasestorage.app',
    iosBundleId: 'com.example.cookWithEngineer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjo1LA_kDIjGpwoJdGAgr8nc4T3gllxms',
    appId: '1:942621156943:web:fb452e3f3f56504072ac3a',
    messagingSenderId: '942621156943',
    projectId: 'newsapp-4210a',
    authDomain: 'newsapp-4210a.firebaseapp.com',
    databaseURL: 'https://newsapp-4210a-default-rtdb.firebaseio.com',
    storageBucket: 'newsapp-4210a.firebasestorage.app',
    measurementId: 'G-QF0F7XM5WG',
  );
}
